/**
 * SEO helpers — small functions that return JSON-LD payloads for the
 * various schema.org types Google rewards with rich snippets.
 *
 * Every tool page already embeds FAQPage + WebApplication schemas
 * inline. These helpers add the next-tier signals:
 *
 *   - HowTo          → step-by-step rich result
 *   - BreadcrumbList → site-hierarchy result + breadcrumb in SERP
 *   - Organization   → knowledge-panel signal (added once in layout)
 *   - WebSite + SearchAction → sitelinks + site search box
 *
 * Keeping these as plain JS objects (not strings) lets callers
 * JSON.stringify them inline inside a <script type="application/ld+json">.
 */

const SITE = "https://www.getpdftool.com";

export type HowToStep = { name: string; text: string };

/**
 * HowTo schema. Powers Google's "How to do X" rich result, which can
 * appear as a numbered list directly in search results.
 */
export function howToJsonLd(opts: {
  name: string;
  description: string;
  steps: HowToStep[];
  url: string;
  totalTimeISO?: string; // e.g. "PT2M" for 2 minutes
}) {
  return {
    "@context": "https://schema.org",
    "@type": "HowTo",
    name: opts.name,
    description: opts.description,
    url: opts.url,
    totalTime: opts.totalTimeISO ?? "PT1M",
    step: opts.steps.map((s, i) => ({
      "@type": "HowToStep",
      position: i + 1,
      name: s.name,
      text: s.text,
    })),
  };
}

/**
 * Breadcrumb schema. Tells Google the navigational hierarchy and
 * sometimes replaces the URL in the SERP with the breadcrumb path.
 */
export function breadcrumbJsonLd(items: { name: string; url: string }[]) {
  return {
    "@context": "https://schema.org",
    "@type": "BreadcrumbList",
    itemListElement: items.map((it, i) => ({
      "@type": "ListItem",
      position: i + 1,
      name: it.name,
      item: it.url,
    })),
  };
}

/**
 * Organization schema — one per site, embedded in the root layout.
 * Helps Google build a knowledge-panel sidebar for branded queries
 * ("GetPDFTool"). Required for sitelinks and brand SERPs.
 */
export function organizationJsonLd() {
  return {
    "@context": "https://schema.org",
    "@type": "Organization",
    name: "GetPDFTool",
    url: SITE,
    // Auto-generated by app/opengraph-image.tsx — served as a PNG at
    // /opengraph-image. Used by Google's knowledge-panel.
    logo: `${SITE}/opengraph-image`,
    description:
      "Free online PDF editor and tools. Edit, merge, split, compress, sign and convert PDFs in your browser.",
    sameAs: [
      // Add real social profiles here when you create them — currently
      // empty array signals "brand exists, no social yet".
    ],
  };
}

/**
 * WebSite + SearchAction schema. Tells Google our site has a search
 * box; if it appears in SERPs it gets an inline search box.
 */
export function webSiteJsonLd() {
  return {
    "@context": "https://schema.org",
    "@type": "WebSite",
    name: "GetPDFTool",
    url: SITE,
    potentialAction: {
      "@type": "SearchAction",
      target: `${SITE}/?q={search_term_string}`,
      "query-input": "required name=search_term_string",
    },
  };
}

/** Helper to emit a script tag with stringified JSON-LD. Server-only. */
export function ldScriptProps(data: object) {
  return {
    type: "application/ld+json" as const,
    dangerouslySetInnerHTML: { __html: JSON.stringify(data) },
  };
}
